
package co.matisses.bcs.b1ws.ws.journalentries;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JournalEntriesService", targetNamespace = "JournalEntriesService", wsdlLocation = "http://192.168.5.76/B1WS/WebReferences/JournalEntriesService.wsdl")
public class JournalEntriesService
    extends Service
{

    private final static URL JOURNALENTRIESSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOURNALENTRIESSERVICE_EXCEPTION;
    private final static QName JOURNALENTRIESSERVICE_QNAME = new QName("JournalEntriesService", "JournalEntriesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.76/B1WS/WebReferences/JournalEntriesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOURNALENTRIESSERVICE_WSDL_LOCATION = url;
        JOURNALENTRIESSERVICE_EXCEPTION = e;
    }

    public JournalEntriesService() {
        super(__getWsdlLocation(), JOURNALENTRIESSERVICE_QNAME);
    }

    public JournalEntriesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOURNALENTRIESSERVICE_QNAME, features);
    }

    public JournalEntriesService(URL wsdlLocation) {
        super(wsdlLocation, JOURNALENTRIESSERVICE_QNAME);
    }

    public JournalEntriesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOURNALENTRIESSERVICE_QNAME, features);
    }

    public JournalEntriesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JournalEntriesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JournalEntriesServiceSoap
     */
    @WebEndpoint(name = "JournalEntriesServiceSoap")
    public JournalEntriesServiceSoap getJournalEntriesServiceSoap() {
        return super.getPort(new QName("JournalEntriesService", "JournalEntriesServiceSoap"), JournalEntriesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JournalEntriesServiceSoap
     */
    @WebEndpoint(name = "JournalEntriesServiceSoap")
    public JournalEntriesServiceSoap getJournalEntriesServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("JournalEntriesService", "JournalEntriesServiceSoap"), JournalEntriesServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns JournalEntriesServiceSoap
     */
    @WebEndpoint(name = "JournalEntriesServiceSoap12")
    public JournalEntriesServiceSoap getJournalEntriesServiceSoap12() {
        return super.getPort(new QName("JournalEntriesService", "JournalEntriesServiceSoap12"), JournalEntriesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JournalEntriesServiceSoap
     */
    @WebEndpoint(name = "JournalEntriesServiceSoap12")
    public JournalEntriesServiceSoap getJournalEntriesServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("JournalEntriesService", "JournalEntriesServiceSoap12"), JournalEntriesServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOURNALENTRIESSERVICE_EXCEPTION!= null) {
            throw JOURNALENTRIESSERVICE_EXCEPTION;
        }
        return JOURNALENTRIESSERVICE_WSDL_LOCATION;
    }

}
