package co.matisses.bcs.b1ws.ws.activities;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "ActivitiesService", targetNamespace = "ActivitiesService", wsdlLocation = "http://192.168.5.75/B1WS/WebReferences/ActivitiesService.wsdl")
public class ActivitiesService
        extends Service {

    private final static URL ACTIVITIESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITIESSERVICE_EXCEPTION;
    private final static QName ACTIVITIESSERVICE_QNAME = new QName("ActivitiesService", "ActivitiesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.75/B1WS/WebReferences/ActivitiesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITIESSERVICE_WSDL_LOCATION = url;
        ACTIVITIESSERVICE_EXCEPTION = e;
    }

    public ActivitiesService() {
        super(__getWsdlLocation(), ACTIVITIESSERVICE_QNAME);
    }

    public ActivitiesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITIESSERVICE_QNAME, features);
    }

    public ActivitiesService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITIESSERVICE_QNAME);
    }

    public ActivitiesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITIESSERVICE_QNAME, features);
    }

    public ActivitiesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivitiesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns ActivitiesServiceSoap
     */
    @WebEndpoint(name = "ActivitiesServiceSoap")
    public ActivitiesServiceSoap getActivitiesServiceSoap() {
        return super.getPort(new QName("ActivitiesService", "ActivitiesServiceSoap"), ActivitiesServiceSoap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns ActivitiesServiceSoap
     */
    @WebEndpoint(name = "ActivitiesServiceSoap")
    public ActivitiesServiceSoap getActivitiesServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("ActivitiesService", "ActivitiesServiceSoap"), ActivitiesServiceSoap.class, features);
    }

    /**
     *
     * @return returns ActivitiesServiceSoap
     */
    @WebEndpoint(name = "ActivitiesServiceSoap12")
    public ActivitiesServiceSoap getActivitiesServiceSoap12() {
        return super.getPort(new QName("ActivitiesService", "ActivitiesServiceSoap12"), ActivitiesServiceSoap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns ActivitiesServiceSoap
     */
    @WebEndpoint(name = "ActivitiesServiceSoap12")
    public ActivitiesServiceSoap getActivitiesServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("ActivitiesService", "ActivitiesServiceSoap12"), ActivitiesServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITIESSERVICE_EXCEPTION != null) {
            throw ACTIVITIESSERVICE_EXCEPTION;
        }
        return ACTIVITIESSERVICE_WSDL_LOCATION;
    }
}
