package co.matisses.bcs.b1ws.ws.activities;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebService(name = "ActivitiesServiceSoap", targetNamespace = "ActivitiesService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ActivitiesServiceSoap {

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.activities.AddActivityResponse
     */
    @WebMethod(operationName = "AddActivity", action = "ActivitiesService/AddActivity")
    @WebResult(name = "AddActivityResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public AddActivityResponse addActivity(
            @WebParam(name = "AddActivity", targetNamespace = "ActivitiesService", partName = "parameters") AddActivity parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.activities.UpdateActivityResponse
     */
    @WebMethod(operationName = "UpdateActivity", action = "ActivitiesService/UpdateActivity")
    @WebResult(name = "UpdateActivityResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public UpdateActivityResponse updateActivity(
            @WebParam(name = "UpdateActivity", targetNamespace = "ActivitiesService", partName = "parameters") UpdateActivity parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.activities.DeleteActivityResponse
     */
    @WebMethod(operationName = "DeleteActivity", action = "ActivitiesService/DeleteActivity")
    @WebResult(name = "DeleteActivityResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public DeleteActivityResponse deleteActivity(
            @WebParam(name = "DeleteActivity", targetNamespace = "ActivitiesService", partName = "parameters") DeleteActivity parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.activities.GetActivityResponse
     */
    @WebMethod(operationName = "GetActivity", action = "ActivitiesService/GetActivity")
    @WebResult(name = "GetActivityResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetActivityResponse getActivity(
            @WebParam(name = "GetActivity", targetNamespace = "ActivitiesService", partName = "parameters") GetActivity parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.activities.GetActivityListResponse
     */
    @WebMethod(operationName = "GetActivityList", action = "ActivitiesService/GetActivityList")
    @WebResult(name = "GetActivityListResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetActivityListResponse getActivityList(
            @WebParam(name = "GetActivityList", targetNamespace = "ActivitiesService", partName = "parameters") GetActivityList parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns
     * co.matisses.b1ws.activities.GetSingleInstanceFromSeriesResponse
     */
    @WebMethod(operationName = "GetSingleInstanceFromSeries", action = "ActivitiesService/GetSingleInstanceFromSeries")
    @WebResult(name = "GetSingleInstanceFromSeriesResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetSingleInstanceFromSeriesResponse getSingleInstanceFromSeries(
            @WebParam(name = "GetSingleInstanceFromSeries", targetNamespace = "ActivitiesService", partName = "parameters") GetSingleInstanceFromSeries parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns
     * co.matisses.b1ws.activities.UpdateSingleInstanceInSeriesResponse
     */
    @WebMethod(operationName = "UpdateSingleInstanceInSeries", action = "ActivitiesService/UpdateSingleInstanceInSeries")
    @WebResult(name = "UpdateSingleInstanceInSeriesResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public UpdateSingleInstanceInSeriesResponse updateSingleInstanceInSeries(
            @WebParam(name = "UpdateSingleInstanceInSeries", targetNamespace = "ActivitiesService", partName = "parameters") UpdateSingleInstanceInSeries parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns
     * co.matisses.b1ws.activities.DeleteSingleInstanceFromSeriesResponse
     */
    @WebMethod(operationName = "DeleteSingleInstanceFromSeries", action = "ActivitiesService/DeleteSingleInstanceFromSeries")
    @WebResult(name = "DeleteSingleInstanceFromSeriesResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public DeleteSingleInstanceFromSeriesResponse deleteSingleInstanceFromSeries(
            @WebParam(name = "DeleteSingleInstanceFromSeries", targetNamespace = "ActivitiesService", partName = "parameters") DeleteSingleInstanceFromSeries parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns
     * co.matisses.b1ws.activities.GetTopNActivityInstancesResponse
     */
    @WebMethod(operationName = "GetTopNActivityInstances", action = "ActivitiesService/GetTopNActivityInstances")
    @WebResult(name = "GetTopNActivityInstancesResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetTopNActivityInstancesResponse getTopNActivityInstances(
            @WebParam(name = "GetTopNActivityInstances", targetNamespace = "ActivitiesService", partName = "parameters") GetTopNActivityInstances parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);
}
