package co.matisses.bcs.b1ws.ws.serviceCalls;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebService(name = "ServiceCallsServiceSoap", targetNamespace = "ServiceCallsService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceCallsServiceSoap {

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.servicecalls.AddResponse
     */
    @WebMethod(operationName = "Add", action = "ServiceCallsService/Add")
    @WebResult(name = "AddResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public AddResponse add(
            @WebParam(name = "Add", targetNamespace = "ServiceCallsService", partName = "parameters") Add parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.servicecalls.UpdateResponse
     */
    @WebMethod(operationName = "Update", action = "ServiceCallsService/Update")
    @WebResult(name = "UpdateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public UpdateResponse update(
            @WebParam(name = "Update", targetNamespace = "ServiceCallsService", partName = "parameters") Update parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.servicecalls.RemoveResponse
     */
    @WebMethod(operationName = "Remove", action = "ServiceCallsService/Remove")
    @WebResult(name = "RemoveResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public RemoveResponse remove(
            @WebParam(name = "Remove", targetNamespace = "ServiceCallsService", partName = "parameters") Remove parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.servicecalls.GetByParamsResponse
     */
    @WebMethod(operationName = "GetByParams", action = "ServiceCallsService/GetByParams")
    @WebResult(name = "GetByParamsResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetByParamsResponse getByParams(
            @WebParam(name = "GetByParams", targetNamespace = "ServiceCallsService", partName = "parameters") GetByParams parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return returns co.matisses.b1ws.servicecalls.CloseResponse
     */
    @WebMethod(operationName = "Close", action = "ServiceCallsService/Close")
    @WebResult(name = "CloseResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public CloseResponse close(
            @WebParam(name = "Close", targetNamespace = "ServiceCallsService", partName = "parameters") Close parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header") MsgHeader requestHeader);
}
