
package co.matisses.bcs.b1ws.ws.warehousesublevelcodes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WarehouseSublevelCodesServiceSoap", targetNamespace = "WarehouseSublevelCodesService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WarehouseSublevelCodesServiceSoap {


    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.warehousesublevelcodes.GetResponse
     */
    @WebMethod(operationName = "Get", action = "WarehouseSublevelCodesService/Get")
    @WebResult(name = "GetResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetResponse get(
        @WebParam(name = "Get", targetNamespace = "WarehouseSublevelCodesService", partName = "parameters")
        Get parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.warehousesublevelcodes.AddResponse
     */
    @WebMethod(operationName = "Add", action = "WarehouseSublevelCodesService/Add")
    @WebResult(name = "AddResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public AddResponse add(
        @WebParam(name = "Add", targetNamespace = "WarehouseSublevelCodesService", partName = "parameters")
        Add parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.warehousesublevelcodes.UpdateResponse
     */
    @WebMethod(operationName = "Update", action = "WarehouseSublevelCodesService/Update")
    @WebResult(name = "UpdateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public UpdateResponse update(
        @WebParam(name = "Update", targetNamespace = "WarehouseSublevelCodesService", partName = "parameters")
        Update parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.warehousesublevelcodes.DeleteResponse
     */
    @WebMethod(operationName = "Delete", action = "WarehouseSublevelCodesService/Delete")
    @WebResult(name = "DeleteResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public DeleteResponse delete(
        @WebParam(name = "Delete", targetNamespace = "WarehouseSublevelCodesService", partName = "parameters")
        Delete parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.warehousesublevelcodes.GetListResponse
     */
    @WebMethod(operationName = "GetList", action = "WarehouseSublevelCodesService/GetList")
    @WebResult(name = "GetListResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetListResponse getList(
        @WebParam(name = "GetList", targetNamespace = "WarehouseSublevelCodesService", partName = "parameters")
        GetList parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

}
