
package co.matisses.bcs.b1ws.ws.goodsissue;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventoryGenExitService", targetNamespace = "InventoryGenExitService", wsdlLocation = "http://192.168.5.76/B1WS/WebReferences/InventoryGenExitService.wsdl")
public class InventoryGenExitService
    extends Service
{

    private final static URL INVENTORYGENEXITSERVICE_WSDL_LOCATION;
    private final static WebServiceException INVENTORYGENEXITSERVICE_EXCEPTION;
    private final static QName INVENTORYGENEXITSERVICE_QNAME = new QName("InventoryGenExitService", "InventoryGenExitService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.76/B1WS/WebReferences/InventoryGenExitService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTORYGENEXITSERVICE_WSDL_LOCATION = url;
        INVENTORYGENEXITSERVICE_EXCEPTION = e;
    }

    public InventoryGenExitService() {
        super(__getWsdlLocation(), INVENTORYGENEXITSERVICE_QNAME);
    }

    public InventoryGenExitService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORYGENEXITSERVICE_QNAME, features);
    }

    public InventoryGenExitService(URL wsdlLocation) {
        super(wsdlLocation, INVENTORYGENEXITSERVICE_QNAME);
    }

    public InventoryGenExitService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORYGENEXITSERVICE_QNAME, features);
    }

    public InventoryGenExitService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryGenExitService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventoryGenExitServiceSoap
     */
    @WebEndpoint(name = "InventoryGenExitServiceSoap")
    public InventoryGenExitServiceSoap getInventoryGenExitServiceSoap() {
        return super.getPort(new QName("InventoryGenExitService", "InventoryGenExitServiceSoap"), InventoryGenExitServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryGenExitServiceSoap
     */
    @WebEndpoint(name = "InventoryGenExitServiceSoap")
    public InventoryGenExitServiceSoap getInventoryGenExitServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("InventoryGenExitService", "InventoryGenExitServiceSoap"), InventoryGenExitServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns InventoryGenExitServiceSoap
     */
    @WebEndpoint(name = "InventoryGenExitServiceSoap12")
    public InventoryGenExitServiceSoap getInventoryGenExitServiceSoap12() {
        return super.getPort(new QName("InventoryGenExitService", "InventoryGenExitServiceSoap12"), InventoryGenExitServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryGenExitServiceSoap
     */
    @WebEndpoint(name = "InventoryGenExitServiceSoap12")
    public InventoryGenExitServiceSoap getInventoryGenExitServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("InventoryGenExitService", "InventoryGenExitServiceSoap12"), InventoryGenExitServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORYGENEXITSERVICE_EXCEPTION!= null) {
            throw INVENTORYGENEXITSERVICE_EXCEPTION;
        }
        return INVENTORYGENEXITSERVICE_WSDL_LOCATION;
    }

}
