
package co.matisses.bcs.b1ws.ws.binlocations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BinLocationsService", targetNamespace = "BinLocationsService", wsdlLocation = "http://192.168.5.76/B1WS/WebReferences/BinLocationsService.wsdl")
public class BinLocationsService
    extends Service
{

    private final static URL BINLOCATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BINLOCATIONSSERVICE_EXCEPTION;
    private final static QName BINLOCATIONSSERVICE_QNAME = new QName("BinLocationsService", "BinLocationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.76/B1WS/WebReferences/BinLocationsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BINLOCATIONSSERVICE_WSDL_LOCATION = url;
        BINLOCATIONSSERVICE_EXCEPTION = e;
    }

    public BinLocationsService() {
        super(__getWsdlLocation(), BINLOCATIONSSERVICE_QNAME);
    }

    public BinLocationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BINLOCATIONSSERVICE_QNAME, features);
    }

    public BinLocationsService(URL wsdlLocation) {
        super(wsdlLocation, BINLOCATIONSSERVICE_QNAME);
    }

    public BinLocationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BINLOCATIONSSERVICE_QNAME, features);
    }

    public BinLocationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BinLocationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BinLocationsServiceSoap
     */
    @WebEndpoint(name = "BinLocationsServiceSoap")
    public BinLocationsServiceSoap getBinLocationsServiceSoap() {
        return super.getPort(new QName("BinLocationsService", "BinLocationsServiceSoap"), BinLocationsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BinLocationsServiceSoap
     */
    @WebEndpoint(name = "BinLocationsServiceSoap")
    public BinLocationsServiceSoap getBinLocationsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("BinLocationsService", "BinLocationsServiceSoap"), BinLocationsServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns BinLocationsServiceSoap
     */
    @WebEndpoint(name = "BinLocationsServiceSoap12")
    public BinLocationsServiceSoap getBinLocationsServiceSoap12() {
        return super.getPort(new QName("BinLocationsService", "BinLocationsServiceSoap12"), BinLocationsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BinLocationsServiceSoap
     */
    @WebEndpoint(name = "BinLocationsServiceSoap12")
    public BinLocationsServiceSoap getBinLocationsServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("BinLocationsService", "BinLocationsServiceSoap12"), BinLocationsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BINLOCATIONSSERVICE_EXCEPTION!= null) {
            throw BINLOCATIONSSERVICE_EXCEPTION;
        }
        return BINLOCATIONSSERVICE_WSDL_LOCATION;
    }

}
