
package co.matisses.bcs.b1ws.ws.binlocations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BinLocationsServiceSoap", targetNamespace = "BinLocationsService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BinLocationsServiceSoap {


    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.binlocation.GetResponse
     */
    @WebMethod(operationName = "Get", action = "BinLocationsService/Get")
    @WebResult(name = "GetResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetResponse get(
        @WebParam(name = "Get", targetNamespace = "BinLocationsService", partName = "parameters")
        Get parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.binlocation.AddResponse
     */
    @WebMethod(operationName = "Add", action = "BinLocationsService/Add")
    @WebResult(name = "AddResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public AddResponse add(
        @WebParam(name = "Add", targetNamespace = "BinLocationsService", partName = "parameters")
        Add parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.binlocation.UpdateResponse
     */
    @WebMethod(operationName = "Update", action = "BinLocationsService/Update")
    @WebResult(name = "UpdateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public UpdateResponse update(
        @WebParam(name = "Update", targetNamespace = "BinLocationsService", partName = "parameters")
        Update parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.binlocation.DeleteResponse
     */
    @WebMethod(operationName = "Delete", action = "BinLocationsService/Delete")
    @WebResult(name = "DeleteResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public DeleteResponse delete(
        @WebParam(name = "Delete", targetNamespace = "BinLocationsService", partName = "parameters")
        Delete parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.matisses.b1ws.binlocation.GetListResponse
     */
    @WebMethod(operationName = "GetList", action = "BinLocationsService/GetList")
    @WebResult(name = "GetListResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetListResponse getList(
        @WebParam(name = "GetList", targetNamespace = "BinLocationsService", partName = "parameters")
        GetList parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

}
