
package co.matisses.bcs.b1ws.ws.quotations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuotationsService", targetNamespace = "QuotationsService", wsdlLocation = "http://192.168.5.75/B1WS/WebReferences/QuotationsService.wsdl")
public class QuotationsService
    extends Service
{

    private final static URL QUOTATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUOTATIONSSERVICE_EXCEPTION;
    private final static QName QUOTATIONSSERVICE_QNAME = new QName("QuotationsService", "QuotationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.75/B1WS/WebReferences/QuotationsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUOTATIONSSERVICE_WSDL_LOCATION = url;
        QUOTATIONSSERVICE_EXCEPTION = e;
    }

    public QuotationsService() {
        super(__getWsdlLocation(), QUOTATIONSSERVICE_QNAME);
    }

    public QuotationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUOTATIONSSERVICE_QNAME, features);
    }

    public QuotationsService(URL wsdlLocation) {
        super(wsdlLocation, QUOTATIONSSERVICE_QNAME);
    }

    public QuotationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUOTATIONSSERVICE_QNAME, features);
    }

    public QuotationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuotationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuotationsServiceSoap
     */
    @WebEndpoint(name = "QuotationsServiceSoap")
    public QuotationsServiceSoap getQuotationsServiceSoap() {
        return super.getPort(new QName("QuotationsService", "QuotationsServiceSoap"), QuotationsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuotationsServiceSoap
     */
    @WebEndpoint(name = "QuotationsServiceSoap")
    public QuotationsServiceSoap getQuotationsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("QuotationsService", "QuotationsServiceSoap"), QuotationsServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns QuotationsServiceSoap
     */
    @WebEndpoint(name = "QuotationsServiceSoap12")
    public QuotationsServiceSoap getQuotationsServiceSoap12() {
        return super.getPort(new QName("QuotationsService", "QuotationsServiceSoap12"), QuotationsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuotationsServiceSoap
     */
    @WebEndpoint(name = "QuotationsServiceSoap12")
    public QuotationsServiceSoap getQuotationsServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("QuotationsService", "QuotationsServiceSoap12"), QuotationsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUOTATIONSSERVICE_EXCEPTION!= null) {
            throw QUOTATIONSSERVICE_EXCEPTION;
        }
        return QUOTATIONSSERVICE_WSDL_LOCATION;
    }

}
