
package co.matisses.bcs.b1ws.ws.employeesinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeesInfoService", targetNamespace = "EmployeesInfoService", wsdlLocation = "http://192.168.5.75/B1WS/WebReferences/EmployeesInfoService.wsdl")
public class EmployeesInfoService
    extends Service
{

    private final static URL EMPLOYEESINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESINFOSERVICE_EXCEPTION;
    private final static QName EMPLOYEESINFOSERVICE_QNAME = new QName("EmployeesInfoService", "EmployeesInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.75/B1WS/WebReferences/EmployeesInfoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESINFOSERVICE_WSDL_LOCATION = url;
        EMPLOYEESINFOSERVICE_EXCEPTION = e;
    }

    public EmployeesInfoService() {
        super(__getWsdlLocation(), EMPLOYEESINFOSERVICE_QNAME);
    }

    public EmployeesInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESINFOSERVICE_QNAME, features);
    }

    public EmployeesInfoService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESINFOSERVICE_QNAME);
    }

    public EmployeesInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESINFOSERVICE_QNAME, features);
    }

    public EmployeesInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeesInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeesInfoServiceSoap
     */
    @WebEndpoint(name = "EmployeesInfoServiceSoap")
    public EmployeesInfoServiceSoap getEmployeesInfoServiceSoap() {
        return super.getPort(new QName("EmployeesInfoService", "EmployeesInfoServiceSoap"), EmployeesInfoServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeesInfoServiceSoap
     */
    @WebEndpoint(name = "EmployeesInfoServiceSoap")
    public EmployeesInfoServiceSoap getEmployeesInfoServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("EmployeesInfoService", "EmployeesInfoServiceSoap"), EmployeesInfoServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns EmployeesInfoServiceSoap
     */
    @WebEndpoint(name = "EmployeesInfoServiceSoap12")
    public EmployeesInfoServiceSoap getEmployeesInfoServiceSoap12() {
        return super.getPort(new QName("EmployeesInfoService", "EmployeesInfoServiceSoap12"), EmployeesInfoServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeesInfoServiceSoap
     */
    @WebEndpoint(name = "EmployeesInfoServiceSoap12")
    public EmployeesInfoServiceSoap getEmployeesInfoServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("EmployeesInfoService", "EmployeesInfoServiceSoap12"), EmployeesInfoServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESINFOSERVICE_EXCEPTION!= null) {
            throw EMPLOYEESINFOSERVICE_EXCEPTION;
        }
        return EMPLOYEESINFOSERVICE_WSDL_LOCATION;
    }

}
