
package co.matisses.bcs.b1ws.ws.creditnotes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditNotesService", targetNamespace = "CreditNotesService", wsdlLocation = "http://192.168.5.76/B1WS/WebReferences/CreditNotesService.wsdl")
public class CreditNotesService
    extends Service
{

    private final static URL CREDITNOTESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITNOTESSERVICE_EXCEPTION;
    private final static QName CREDITNOTESSERVICE_QNAME = new QName("CreditNotesService", "CreditNotesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.76/B1WS/WebReferences/CreditNotesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITNOTESSERVICE_WSDL_LOCATION = url;
        CREDITNOTESSERVICE_EXCEPTION = e;
    }

    public CreditNotesService() {
        super(__getWsdlLocation(), CREDITNOTESSERVICE_QNAME);
    }

    public CreditNotesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITNOTESSERVICE_QNAME, features);
    }

    public CreditNotesService(URL wsdlLocation) {
        super(wsdlLocation, CREDITNOTESSERVICE_QNAME);
    }

    public CreditNotesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITNOTESSERVICE_QNAME, features);
    }

    public CreditNotesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditNotesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditNotesServiceSoap
     */
    @WebEndpoint(name = "CreditNotesServiceSoap")
    public CreditNotesServiceSoap getCreditNotesServiceSoap() {
        return super.getPort(new QName("CreditNotesService", "CreditNotesServiceSoap"), CreditNotesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditNotesServiceSoap
     */
    @WebEndpoint(name = "CreditNotesServiceSoap")
    public CreditNotesServiceSoap getCreditNotesServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("CreditNotesService", "CreditNotesServiceSoap"), CreditNotesServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CreditNotesServiceSoap
     */
    @WebEndpoint(name = "CreditNotesServiceSoap12")
    public CreditNotesServiceSoap getCreditNotesServiceSoap12() {
        return super.getPort(new QName("CreditNotesService", "CreditNotesServiceSoap12"), CreditNotesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditNotesServiceSoap
     */
    @WebEndpoint(name = "CreditNotesServiceSoap12")
    public CreditNotesServiceSoap getCreditNotesServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("CreditNotesService", "CreditNotesServiceSoap12"), CreditNotesServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITNOTESSERVICE_EXCEPTION!= null) {
            throw CREDITNOTESSERVICE_EXCEPTION;
        }
        return CREDITNOTESSERVICE_WSDL_LOCATION;
    }

}
